spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cloud_member
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
#    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 9000

security:
  user:
    name: user
    password: test


logging:
  level:
    root: debug
#    org:
#      springframework:
#        web: DEBUG
#        security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace