server:
  port: 8001

spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/h2/sample-db
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 568047584227-7g883q08cc2r78qm2qj6u9josms28ged.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

keycloak:
  enabled: true
  host: ""
  realm: ""
  cliend_id: ""
  client_secret: ""

