server:
  port: 8001
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3002"
              - "http://localhost:3003"
              - "http://localhost:3011"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
            allowedHeaders:
              - Context-Type
              - Content-Type
              - Accept
              - X-Requested-With
              - remember-me
              - Content-Disposition
              - Authorization
              - ssoKey
              - session
              - newToken
              - access-token
              - Access-Control-Expose-Headers
            allow-credentials: true
      routes:
        - id: protected-resource-api
          uri: http://localhost:8080/
          predicates:
            - Path=/api/**
          filters:
            - JwtValidation
              args:
                publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAibsSqp+vuea8/EtRp7bOV5bBq1mWbAt1AE35l506LBJFFHEy9LWayYXhNnlQNWGifPF0cTKm72m/uj4IogB9nkWnd8ZgH0n6bN2oFxpwHBP46YU7YlAyxKys/loobW/JzAJr54qPS5B/GYxf4GNPvsIdbJoQs/R+RUq7S1rGDltnEKArWHXsSb2B6Iw934GXDiutwwoG4fvNzJBxswmtppjvcJWaYTYJ/m8ungj9vhzcr2Y2gEg++R+7YbcYNqnNf6X4fqNX3J5o3t2RhPwHOODnPZLVqkzSSNDwSxlXvCA4T2NnfSbUTzFBMKp1PYqiFsJi16VQOa0ePbud2FCSDQIDAQAB
                preFilter: true
                postFilter: true
        - id: user-api
          uri: http://localhost:8081/
          predicates:
            - Path=/user/api/**
        - id: dashboard-api
          uri: http://localhost:8090/
          predicates:
            - Path=/dashboard/api/**


  datasource:
    url: jdbc:mariadb://localhost:3306/cloud_member
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  sql:
    init:
      mode: always


logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace