spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cloud_management_platform
    username: agj017
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 9000

logging:
  level:
    root: debug
#    org:
#      springframework:
#        web: DEBUG
#        security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace